import { Teacher, SubRequest } from '../models/app.models';
export const DEFAULT_TEACHERS: Teacher[] = [
  {
    id: 'ana',
    nome: 'Ana Figueiredo',
    disciplinas: ['Matemática', 'Estatística'],
    formacao: 'Licenciatura em Matemática – USP',
    experiencia: 8,
    nota: 4.9,
    subs: 34,
    distancia: '2,1 km',
    cidade: 'São Paulo',
    disponivel: true,
    verificado: true,
    initials: 'AF',
    cor: 'blue',
    bio: 'Professora de Matemática com 8 anos de experiência no Ensino Médio. Metodologia ativa, foco em resolução de problemas.',
    niveis: ['Ensino Fundamental II', 'Ensino Médio'],
  },
  {
    id: 'carlos',
    nome: 'Carlos Mendes',
    disciplinas: ['Matemática', 'Física'],
    formacao: 'Licenciatura em Matemática – UNESP',
    experiencia: 12,
    nota: 4.8,
    subs: 52,
    distancia: '3,4 km',
    cidade: 'São Paulo',
    disponivel: true,
    verificado: true,
    initials: 'CM',
    cor: 'green',
    bio: 'Professor com ampla experiência em preparação para vestibular. Especializado em Matemática e Física para o Ensino Médio.',
    niveis: ['Ensino Médio'],
  },
  {
    id: 'roberto',
    nome: 'Roberto Lima',
    disciplinas: ['Ciências', 'Biologia'],
    formacao: 'Licenciatura em Ciências Biológicas – UNICAMP',
    experiencia: 5,
    nota: 4.6,
    subs: 18,
    distancia: '5,8 km',
    cidade: 'São Paulo',
    disponivel: true,
    verificado: true,
    initials: 'RL',
    cor: 'purple',
    bio: 'Professor de Ciências e Biologia. Experiência com Ensino Fundamental e Médio em escolas públicas e privadas.',
    niveis: ['Ensino Fundamental I', 'Ensino Fundamental II', 'Ensino Médio'],
  },
];

export const DEFAULT_REQUESTS: SubRequest[] = [
  {
    id: 'demo-1',
    disciplina: 'Matemática',
    nivel: 'Ensino Médio',
    turma: '2º Médio A',
    data: '2026-10-25',
    horarioInicio: '07:30',
    horarioFim: '09:10',
    modalidade: 'presencial',
    cidade: 'São Paulo',
    endereco: 'Rua das Palmeiras, 450',
    valor: '120',
    observacoes: 'Conteúdo: Funções do 2º grau. Levar exercícios de revisão.',
    status: 'aguardando',
    professorConvidadoId: 'ana',
    professorConvidadoNome: 'Ana Figueiredo',
    professorConfirmadoId: null,
    professorConfirmadoNome: null,
    criadaEm: new Date().toISOString(),
    instituicaoNome: 'Colégio Horizonte',
    recusadoPorIds: [],
  },
];


